# Generated by Django 2.2.24 on 2024-07-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitordata',
            name='launch_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='launch id'),
        ),
        migrations.AlterField(
            model_name='monitordata',
            name='content_object_repr',
            field=models.CharField(editable=False, max_length=256, verbose_name='content object representation'),
        ),
        migrations.AlterField(
            model_name='resourcedata',
            name='content_object_repr',
            field=models.CharField(editable=False, max_length=256, verbose_name='content object representation'),
        ),
    ]
