# Generated by Django 5.0.13 on 2025-03-17 09:40

import orchestra.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0002_auto_20240711_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='async_actions',
            field=orchestra.models.fields.MultiSelectField(blank=True, choices=[], help_text='Specify individual actions to be executed asynchronoulsy.', max_length=256),
        ),
    ]
