# Generated by Django 2.2.24 on 2024-07-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='ratelimit',
            field=models.CharField(blank=True, choices=[('userbase', 'base'), ('user100', '100'), ('user200', '200'), ('user500', '500')], default='userbase', max_length=100, null=True, verbose_name='ratelimit'),
        ),
    ]
