# Generated by Django 5.0.13 on 2026-01-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0003_alter_bill_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="The date when the invoice was issued.",
                null=True,
                verbose_name="date",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="state",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("sent", "Sent"),
                    ("accepted", "Accepted"),
                    ("registered", "Registered"),
                    ("refused", "Refused"),
                    ("closed", "Closed"),
                    ("error", "Error"),
                ],
                default="new",
                help_text="State of the issued invoice in the remote system.",
                max_length=16,
                verbose_name="state",
            ),
        ),
    ]
