# Generated by Django 2.2.24 on 2024-07-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='billing_point',
            field=models.CharField(choices=[('ON_REGISTER', 'Registration date'), ('ON_FIXED_DATE', 'Every April')], default='ON_FIXED_DATE', help_text='Reference point for calculating the renewal date on recurring invoices', max_length=16, verbose_name='billing point'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order_description',
            field=models.CharField(blank=True, help_text="Python <a href='https://docs.python.org/2/library/functions.html#eval'>expression</a> used for generating the description for the bill lines of this services.<br>Defaults to <tt>'%s: %s' % (gettext(handler.description), instance)</tt>", max_length=256, verbose_name='Order description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='tax',
            field=models.PositiveIntegerField(choices=[(0, 'Duty free'), (21, '21%')], default=21, verbose_name='tax'),
        ),
    ]
