BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBB

BBBBB BBBBBBBBBBBBBBB
    XXXX
    BBB BBBBBBBB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB
        XXXXXXXXXXXX 
        XXXX
            BBB BBBBBBBBB BB BBBBBBBBBB
              XXXXFFFFFFFFFF X BBB BBBBB BB BBBBBBBBBBBBBBBBFFFFFFFFFFXXXXBB BBB BBBBBBBBBBBBXBBBBB BBBBBBXXXXX
            BBBBBB
        XXXXX
        XXXXX
    BBBBBB
    XXXXX
BBBBBBBB
