# Generated by Django 5.0.13 on 2025-09-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_auto_20240711_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='dnssec',
            field=models.BooleanField(default=False, verbose_name='DNSsec'),
        ),
    ]
