# Generated by Django 2.2.28 on 2024-07-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0005_auto_20240711_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webapp',
            name='type',
            field=models.CharField(choices=[('moodle-php', 'Moodle'), ('php', 'PHP'), ('static', 'Static'), ('webalizer', 'Webalizer'), ('wordpress-php', 'WordPress')], max_length=32, verbose_name='type'),
        ),
    ]
