# Generated by Django 2.2.28 on 2024-07-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0006_auto_20240712_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webapp',
            name='type',
            field=models.CharField(choices=[('limesurvey-php', 'Limesurvey'), ('moodle-php', 'Moodle'), ('php', 'PHP'), ('static', 'Static'), ('webalizer', 'Webalizer'), ('wordpress-php', 'WordPress')], max_length=32, verbose_name='type'),
        ),
    ]
