# Generated by Django 5.0.13 on 2025-03-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0007_auto_20240726_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webapp',
            name='type',
            field=models.CharField(choices=[('moodle-php', 'Moodle'), ('php', 'PHP'), ('static', 'Static'), ('webalizer', 'Webalizer'), ('wordpress-php', 'WordPress')], max_length=32, verbose_name='type'),
        ),
    ]
