BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBB
BBBB BBBBBBBBBB BBBBBB BBBBB

BBBBB BBBBBBBBBB

XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
BBBBBBBB


BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
XX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Home') XXXX
BB BBBB XXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXBBBB XXXXXXXX XXXXXXXXBBBBB
XXXXXX
BBBBBBBB

BBBBB BBBBBBB
  XXX XXXXXXXXXXXXXXXXXXXXX
    BBBBB BBBBBBBBBBBBBBBBBB
    XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'View file') XXXX
    XXXXX
    BBBBBBBB
  XXXXX

    XXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXXXBBBBBBBBBB
    BB BBBB
         gettext(u'\n        <p>The following changes will be performed to <tt>%(settings_file)s</tt> file.</p>\n        ') 
        SSSSSS SSSSSSSSS SSSSSSS SSSS SS SSSSSSSSS SS SSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSS
        
        XXXXXXXXXXX
        
        XXXXXX XXXXXXXXXXXXXXXXXXXXX
            BBB BBBB BB BBBB
            
            BBBBBB
        XXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    BBBB
         gettext(u'\n        <p><tt>%(settings_file)s</tt> file will be automatically updated and Orchestra restarted according to your changes.\n        ') 
        SSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSS SSSS SS SSSSSSSSSSSSS SSSSSSS SSS SSSSSSSSS SSSSSSSSS SSSSSSSSS SS SSSS SSSSSSSS
        
        BB BBBBBBBBBBB
        XX XXXXXXXXXXXXXXXXXX
         gettext(u'Please correct the errors below.') 
        XXXX
        
        BBBBB
        
        BBBBBBB BBBBBBBBBB BB BBB BB BBBBBBBB
        BBB BBB BB BBBBBBBB
            XXXXXXXXX XXXXXXXXXXXXXXX
            XXX XXXXFFFFFXXFFFFFFFFFFFFFXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            BBB BBBB BB BBBBBBBB
                  
                  BB BBBBBBBBBBBBB
                  XXXXXXXXXXX
                    BBB BBBBB BB BBBBBBBBBBBBBBBBBBB
                    XXX XXXXXXXXXXXXXBB BBBBBBBBBBBBBXXBBBBXXBBBBBXXXFFFFFFFFXXXXX
                    BBBBBB
                  XXXXXXXXXXXXX
                  BBBBB
                  XXX XXXXXXXBBBBB BBBBBB BBBBBBXX
                  BBB BBBBB BB BBBBBBBBBBBBBBBBBBB
                    XXXX
                    
                    BB BBBBBBBBBBBBB
                      BBB BBBBBB BB BBBBBBBBBBBBBBBBBB
                      
                      BBBBBB
                    BBBBB
                      
                      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBB BBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBBXXXXXX
                      XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX
                  BBBBBB
                  XXXXX
                BBBBBB
                XXXXXXXX
                XXXXXXXXXXX
            BBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    BBBBB
        XXXXXXX
BBBBBBBB
