BBBB BBBBBB

XXXXXX
    XXXXXX
        XXXXXXX
            XXXXXXXXXX X
                XXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXX XXXX XXXX XXXXX
                XXXXXX XXXXXX
                XXXXXXX XXXXX
                XXXXXXXXX XXXXXXXXX
                XXXXXX
                XXXXXXX XX
                XXXXX XX
                XXXXXX XX
                XXXXXXX XXXXX
                XXXXXXXXXXX XXXXXX
            X
            XXXXXXXXXX XXXX X
                XXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX
            X
            XXXXXXXX X
                XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX
                XXXXXXXXXX XXXXX XXXXXXXX
            X
    XXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX
            XXXXXXXX XXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXX
            X
            XXXXXXXX XXXXXXXXXXXXX X
              XXXXXXXX XXX XX X
                XXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXX
              X XXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX
              X
            X
            XXX XXXXX X XX
            XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX XX XXXXXX
        XXXXXXXXX
    XXXXXXX
    XXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXXX
XXXXXXX
