BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBB
BBBB BBBBBBBBBB BBBBBB BBBBB

BBBBB BBBBBBBBBB

XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
BBBBBBBB


BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
XX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Home') XXXX
XXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX XXXX XXXX XXXXXXX
XXXXXX
BBBBBBBB


BBBBB BBBBBBB
XXXXX
     gettext(u'\n    <p>Current <tt>%(settings_file)s</tt> content.</p>\n    ') 
    SSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSSSSS
    
    XXXXXXXXXXX
XXXXXX
BBBBBBBB
