BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBB BBBBBB BBBBBBBBBB


BBBBB BBBBBBBBBBBBBBBBBB
    XXXX
      BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
      XX XXXXXXBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBB BBBBBBBBX XXXXXXXXXXXXXXXXXXXX
         gettext(u'Send pending') SSSS SSSSSSS
      XXXX
    XXXXX
    
BBBBBBBB

