# Generated by Django 2.2.24 on 2024-07-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saas',
            name='service',
            field=models.CharField(choices=[('wordpress', 'WordPress'), ('nextcloud', 'nextCloud')], max_length=32, verbose_name='service'),
        ),
    ]
