# Generated by Django 2.2.28 on 2024-07-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_auto_20240711_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saas',
            name='service',
            field=models.CharField(choices=[('wordpress', 'WordPress'), ('nextcloud', 'nextCloud'), ('phplist', 'phpList')], max_length=32, verbose_name='service'),
        ),
    ]
