# Generated by Django 2.2.28 on 2024-07-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0003_auto_20240712_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saas',
            name='service',
            field=models.CharField(choices=[('wordpress', 'WordPress'), ('nextcloud', 'nextCloud')], max_length=32, verbose_name='service'),
        ),
    ]
