# Generated by Django 5.0.13 on 2025-03-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0004_auto_20240726_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saas',
            name='service',
            field=models.CharField(choices=[('wordpress', 'WordPress'), ('nextcloud', 'nextCloud'), ('phplist', 'phpList')], max_length=32, verbose_name='service'),
        ),
    ]
