BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBB BBBBBB BBBBBBBBBBBB


BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
XX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Home') XXXX
BB BBBBBBBBBBBB
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXFFFFFFFFXXXX
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXFFFFFFFFFFFFFFFFFFXXXX
BBBB
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXX
XXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXFFFFFFFFXXXXBBBBFFFFFFFFBBBBB
BBBBB
BB BBBBBBBBBBB
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Select %(name)s account') SSSSSS SSSSSSSS SSSSSSSXXXX
BBBBB
XXXXXXXX BB BBB gettext(u'Add')  BBBBFFFFFFFFFFFFFFFFFFBBBBB
XXXXXX
BBBBBBBB


BBBBB BBBBBBBBBBBBBBBBBB
BB BBBBBBBB
XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX X X XXXX
     XXXXXXX XXXXXXXX XXXXXXXXX gettext(u'Services') XXXXXXXXX
    BBB BBBBBBB BB BBBBBBBB
     XXXXXXX XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXFFFFFFFFXXXXXXXXX
    BBBBBB
XXXXXXXXXXXXXX
BBBBB
BB BBBBBBBB
XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXX XXX XXXXXX
     XXXXXXX XXXXXXXX XXXXXXXXX gettext(u'Accounts') XXXXXXXXX
    BBB BBBBBBB BB BBBBBBBB
     XXXXXXX XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXFFFFFFFFXXXXXXXXX
    BBBBBB
XXXXXXXXXXXXXX
BBBBB

BBBBBBBB
