BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBB BBBBBBBBBB


BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
XX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Home') XXXX
BB BBBBBBB
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXFFFFFFFFXXXX
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXFFFFFFFFFFFFFFFFFFXXXX
BBBB
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX
BBBBB
XXXXXXXX FFFFFFFF
XXXXXX
BBBBBBBB


BBBBB BBBBBBBBBBBBBBBBBB
XXXX
  BBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBB
  XX XXXXXXBBBBBBBBBBBBBBBBBBBBB BBBBBBB BBBBBBBB BBBBBBBBX XXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBB
     gettext(u'Add %(name)s') SSS SSSSSSSS
    BBBB
     gettext(u'Add %(account)s %(name)s') SSS SSSSSSSSSSS SSSSSSSS
    BBBBB
  XXXX
XXXXX
BBBBBBBB


BBBBB BBBBBBB
  BB BBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXX gettext(u'Filter') XXXXX
      BB BBBBBBB
          XXXX gettext(u'By account') XXXXX
          XXXX
            XXX BB BBB BBBBBBBBBBBBXXXXXXXXXXXXXXXXBBBBBXXX XXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFXXXXXXXXX
            XXX BB BBBBBBBBBBBBXXXXXXXXXXXXXXXXBBBBBXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
      BBBBB
      BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBB
    XXXXXX
  BBBBB
BBBBBBBB

