BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBB BBBBBBBBBB

BBBBB BBBBBBB
BB BBBBBBBBBBBBB
    XXX gettext(u"Deleting the selected %(objects_name)s would result in deleting related objects, but your account doesn't have permission to delete the following types of objects:") SSSSSSSS SSS SSSSSSSS SSSSSSSSSSSSSSSS SSSSS SSSSSS SS SSSSSSSS SSSSSSS SSSSSSSS SSS SSSS SSSSSSS SSSSSSS SSSS SSSSSSSSSS SS SSSSSS SSS SSSSSSSSS SSSSS SS SSSSSSSSXXXX
    XXXX
    BBB BBB BB BBBBBBBBBBBBB
        XXXXXXXXX
    BBBBBB
    XXXXX
BBBB BBBBBBBBB
    XXX gettext(u'Deleting the selected %(objects_name)s would require deleting the following protected related objects:') SSSSSSSS SSS SSSSSSSS SSSSSSSSSSSSSSSS SSSSS SSSSSSS SSSSSSSS SSS SSSSSSSSS SSSSSSSSS SSSSSSS SSSSSSSSXXXX
    XXXX
    BBB BBB BB BBBBBBBBB
        XXXXXXXXX
    BBBBBB
    XXXXX
BBBB
    XXX gettext(u'Are you sure you want to delete the selected %(objects_name)s? All of the following objects and their related items will be deleted:') SSS SSS SSSS SSS SSSS SS SSSSSS SSS SSSSSSSS SSSSSSSSSSSSSSSSS SSS SS SSS SSSSSSSSS SSSSSSS SSS SSSSS SSSSSSS SSSSS SSSS SS SSSSSSSSXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX gettext(u'Objects') XXXXX
    BBB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB
        XXXXFFFFFFFFFFFFFFXXXXX
    BBBBBB
    XXXXX XXXXXXXXX XXXXXXXXXXXXXXBBBBBBBBBB
    XXXXX
    BBB BBB BB BBBBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXFFFFFFFFFFX XX
    BBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XX
    XXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u"Yes, I'm sure") X XX
    XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'No, take me back') XXXX
    XXXXXX
    XXXXXXX
BBBBB
BBBBBBBB

