BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBB BBBBBBBBBB

BBBBB BBBBBBBBB XXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
XX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Home') XXXX
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXX
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXFFFFFFFFXXXX
XXXXXXXX BB BBBBBBB gettext(u'Disable %(objects_name)s') SSSSSSS SSSSSSSSSSSSSSSSBBBB gettext(u'Enable %(objects_name)s') SSSSSS SSSSSSSSSSSSSSSSBBBBB
XXXXXX
BBBBBBBB

BBBBB BBBBBBB
BB BBBBBBBXXX gettext(u'Are you sure you want to disable selected %(objects_name)s?') SSS SSS SSSS SSS SSSS SS SSSSSSS SSSSSSSS SSSSSSSSSSSSSSSSSXXXX
BBBBXXX gettext(u'Are you sure you want to enable selected %(objects_name)s?') SSS SSS SSSS SSS SSSS SS SSSSSS SSSSSSSS SSSSSSSSSSSSSSSSSXXXX
BBBBB
XXXX gettext(u'Objects') XXXXX
BBB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB
    XXXXFFFFFFFFFFFFFFXXXXX
BBBBBB
XXXXX XXXXXXXXX XXXXXXXXXXXXXXBBBBBBBBBB
XXXXX
BBB BBB BB BBBBBBBB
XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXFFFFFFFFFFX XX
BBBBBB
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XX
XXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u"Yes, I'm sure") X XX
XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'No, take me back') XXXX
XXXXXX
XXXXXXX
BBBBBBBB

