BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBB


BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
XX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Home') XXXX
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXFFFFFFFFXXXX
XXXXXXXX  gettext(u'Select %(name)s account') SSSSSS SSSSSSSS SSSSSSS
XXXXXX
BBBBBBBB

