BBBB BBBB BBBBBBBBBB BBBBB
XXXXXX
XXXXXX
    XXXXXXXBBBBB BBBBBXXXXXXX XXXXXXX XXXXXXBBBBBBBBXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    BBBBB BBBBBBBBBBBB
    XXXXXX XXXXXXXXXXXXXXXX
        XXXX X
            XXXXXXXXXX XXXXXX
            XXXXXXX XX XXXX XXXXXXXXXXX
            XXXXXX XXXX XXXXXXXXXXX
            XXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXX
            XXXXXXXXXX XXXXX
            XXXXXX XXXXX
        X
        XXXXX X
            XXXXXX XXXXXX
            XXXXXX XXXXXXXX XXXX XXXXX
        X
        XXXXXXXXXXXXXXXX X
            XXXXXXX XXX XXX XXXX XXXXX
        X
        XXXXXXXXXXX X
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXX XXXXX
        X
        XXXXXXXXX X
            XXXXXXXX XXXX
            XXXXXXX XXX XXX XXXX XXXXX
        X
        XXXXXXXX X
            XXXXXXXXXXX XXXXX
        X
        XX X
            XXXXXXXXXXX XXXXX
        X
        X X
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXX XXXXXXX XXXX XXXXX
        X
    XXXXXXXX
XXXXXXX

XXXXXX
XXXX XXXXXXXXXX gettext(u'Service report generated on')   FFFFXXXXXX
BBB BBBBBBBB BBBBB BB BBBBBBBB
    XXXX X XX XXXXXXFFFFFFFFFXXXXXXXXXXX
    XXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
          gettext(u'account registered on')   FFFFXXXX
        XXX XXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXX gettext(u'Resources') XXXXX
            BB BBBBBBBBBBBBBBBBB
                XXXX
                BBB BBBBBBBB BB BBBBBBBBBBBBBBBBB
                    XXXXXX XXXXXXFFFFFFFFFXX BB BBBBBBBBBBBBB BB BBBBXXXXX XXXXXXX gettext(u'Used') XXXXXXXXXBBBBBBB BBBBBBBBBBBBBBBBBB BB BBBBBB BBBBBBBBBBBBB BB BBBB X BBBBBXXXXX XXXXXXX gettext(u'Allocated') XXXXXXXXXBBBBBXXXX XXXXX
                BBBBBB
                XXXXX
            BBBBB
        
        BBB BBBBB BBBBBBB BB BBBBB
            XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXFFFFFFFFXXXXXXXXX
            XXXX
            BBB BBB BB BBBBBBB
                XXX XXXXXXXXXXXXXXXXXX XXXXXXFFFFFFFFFXXXXXX
                    BB BBB BBBBBBBBBBBB X gettext(u'disabled') XBBBBB
                    FFFFFFFF
                    BB BBBBBBBBBBBBB
                        XXXX
                        BBB BBBBBBBB BB BBBBBBBBBBBBB
                            XXXXXX XXXXXXFFFFFFFFFXX BB BBBBBBBBBBBBB BB BBBBXXXXX XXXXXXX gettext(u'Used') XXXXXXXXXBBBBBBB BBBBBBBBBBBBBBBBBB BB BBBBBB BBBBBBBBBBBBB BB BBBB X BBBBBXXXXX XXXXXXX gettext(u'Allocated') XXXXXXXXXBBBBBXXXX XXXXX
                        BBBBBB
                        XXXXX
                    BBBBB
                XXXXX
            BBBBBB
            XXXXX
        BBBBBB
        XXXXX
    XXXXXX
BBBBBB
XXXXXXX
XXXXXXX
