BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB


BBBBB BBBB
    BB BBBBBBBBBBBBBBB
        XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX XX XXXXXXX XXXXXXX XXX XXXX XXX XX XXXXXXXXXXXXX
        XXXX FFFFFFFFFFFFFFXXXXX
    BBBBB
BBBBBBBB
