# Generated by Django 2.2.24 on 2024-07-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0006_auto_20230705_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='type',
            field=models.CharField(choices=[('mysql', 'MySQL')], default='mysql', max_length=32, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='databaseuser',
            name='type',
            field=models.CharField(choices=[('mysql', 'MySQL')], default='mysql', max_length=32, verbose_name='type'),
        ),
    ]
