BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBB
BBBB BBBBBBBBBB BBBBBB BBBBB

BBBBB BBBBBBBBBB

XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
BBBBBBBB

BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
XX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Home') XXXX
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBXXFFFFFFFFFFFFFFXXXX
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXFFFFFFFFXXXX
BB BBB
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBXXXXXX
XXXXXXXX 
BBBB BBB
XXXXXXXX XX XXXXXXXXXXX gettext(u'Add')  XXXX
XXXXXXXX 
BBBB
XXXXXXXX  XXXXXXXX XXXXXXX
BBBBB
XXXXXX
BBBBBBBB

BBBBB BBBBBBB
  XXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
    BBBBB BBBBBBBBBBBB
    XXXXXX XXXXXXXX XXXX XXX BBB BBBB BB BBBBBBBBBB BBB BBBBBBBBBBBBX BBBBBBBBBBBX
    BBBBBBBB
    XXXX FFFFFFFFFFFFFFXXXXX
    XXXXX XXXXXXXXX XXXXXXXXXXXXXXBBBBBBBBBB
        XXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXX
        
        BBBBB BBBBBBBBB
        BBBBBBBB
        XXXX XXXXXXXXXXXXXXX XX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                BBB B BB BBBBBBBBBBBBBXXXXXXBBBBBB
                XX XXXXXXXXXXXXXFFFFXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                
                XXXXXX XXXXXXXXXXXXXXX
                
                XX XXXXXXXXXXXXXFFFFXXXX
            XXXXXX
        XXXXXX
        BBBBB BBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XX
            
            XXXXXX XXXXXXXXXXXXXXXX
            
            XX XXXXXXXXXXXXXFFFFXXXX
        XXXXXX
        BBBBBBBB
        XXXXXXXXXXX
    XXXXX
    BBB BBB BB BBBBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXFFFFFFFFFFX XX
    BBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX XX
    XXXXXX XXXXXXXXXXXXX XXXXXXX _("Save") X XX
    XXXXXX
    XXXXXXX
BBBBBBBB

