BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBB
BBBB BBBBBBBBBB BBBBBB BBBBB

BBBBB BBBBBBBBBBBB
XXX XXXXXXXXXXX XXX BBB BBBB BB BBBBBBBBBB BBB BBBBBBBBBBBBX BBBBBBBBBBB XXXXXX XXXXXXXX
BBBBBBBB


BBBBB BBBBBBBBB
XXXX XXXXXXXXXXXXXXX XX
    
    XXXXXX XXXXXXXXXXXXXXXX
    BBB B BB BBBBBBBBBBBBBXXXXXXBBBBBB
    XX XXXXXXXXXXXXXFFFFXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBB
XXXX XXXXXXXXXXXXXXX XX
    
    XXXXXX XXXXXXXXXXXXXXXX
    BBB B BB BBBBBBBBBBBBBXXXXXXBBBBBB
    XX XXXXXXXXXXXXXFFFFXXXX
XXXXXX
BBBBBBBB
