# Generated by Django 2.2.24 on 2024-07-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemusers', '0002_squashed_0004_auto_20210330_1049'),
        ('systemusers', '0003_auto_20230724_1813'),
    ]

    operations = [
    ]
