# Generated by Django 2.2.28 on 2023-11-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemusers', '0002_auto_20150429_1413_squashed_0004_auto_20210330_1049'),
        ('systemusers', '0004_auto_20230813_0920'),
    ]

    operations = [
    ]
