# Generated by Django 2.2.24 on 2024-07-11 12:25

from django.db import migrations, models
import orchestra.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('systemusers', '0004_merge_20240711_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='shell',
            field=models.CharField(choices=[('/dev/null', 'No shell, FTP only'), ('/bin/rssh', 'No shell, SFTP/RSYNC only'), ('/usr/bin/git-shell', 'No shell, GIT only'), ('/bin/bash', '/bin/bash')], default='/dev/null', max_length=32, verbose_name='shell'),
        ),
        migrations.AlterField(
            model_name='webappusers',
            name='username',
            field=models.CharField(help_text='Required. 32 characters or fewer. Letters, digits and ./-/_ only.', max_length=32, validators=[orchestra.core.validators.validate_username], verbose_name='username'),
        ),
    ]
