# Generated by Django 2.2.24 on 2024-07-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsource',
            name='method',
            field=models.CharField(choices=[('SEPADirectDebit', 'SEPA Direct Debit')], max_length=32, verbose_name='method'),
        ),
    ]
