# Generated by Django 5.0.13 on 2025-10-20 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bills", "0003_alter_bill_account"),
        ("bills", "0003_alter_bill_account"),
        ("bills", "0003_alter_bill_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="B2BContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_synced_at", models.DateTimeField(auto_now_add=True)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                (
                    "orchestra_contact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bills.billcontact",
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("status", models.CharField(default="synced", max_length=20)),
                ("remote_id", models.BigIntegerField(null=True)),
            ],
            options={
                "unique_together": {("remote_id", "orchestra_contact")},
            },
        ),
    ]
