# Generated by Django 5.0.13 on 2025-11-26 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("b2brouter", "0001_initial"),
        ("bills", "0003_alter_bill_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="B2BInvoice",
            fields=[
                (
                    "orchestra_bill",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="bills.bill",
                    ),
                ),
                ("remote_id", models.BigIntegerField(null=True)),
                ("first_synced_at", models.DateTimeField(auto_now_add=True)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="synced", max_length=20)),
                ("message", models.TextField(blank=True, default="")),
            ],
            options={
                "unique_together": {("orchestra_bill", "remote_id")},
            },
        ),
    ]
