# Generated by Django 5.0.13 on 2026-05-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0003_alter_bill_account"),
        ("b2brouter", "0002_b2binvoice"),
    ]

    operations = [
        migrations.DeleteModel(
            name="B2BContact",
        ),
        migrations.CreateModel(
            name="B2BContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remote_id", models.BigIntegerField(null=True, unique=True)),
                ("first_synced_at", models.DateTimeField(auto_now_add=True)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="synced", max_length=20)),
                ("message", models.TextField(blank=True, default="")),
                ("vat_key", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="B2BContactBinding",
            fields=[
                (
                    "bill_contact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="b2b_binding",
                        serialize=False,
                        to="bills.billcontact",
                    ),
                ),
                (
                    "b2b_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_contact_bindings",
                        to="b2brouter.b2bcontact",
                    ),
                ),
            ],
        ),
    ]
