# Generated by Django 5.0.13 on 2025-08-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_bannedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='extra_firewall',
            field=models.BooleanField(default=False, verbose_name='block IA'),
        ),
    ]
