BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBB
BBBB BBBBBBBBBB BBBBBB BBBBB


BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
     XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXX
        XXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
    XXXXXXXX
    XXXXXXX
    BBB BBBBBB BBBBBB BB BBBBBBB
        XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXBBBBXXXXBBBBBXX
            XXXXXXXXX
            XXXXBB BBBBBBBBXX XXXXXX FFFFFFFFFXXXXXXBBBBBXXXXX
            XXXXXX XXXXXX FFFFFFFFFXXXXXXXXXXX
            XXXXXX XXXXXX FFFFFFFFFXXXXXXXXXXX
            XXXXXX XXXXXX FFFFFFFFFXXXXXXXXXXX
            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
            XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBXXXBBBBXXBBBBBXXXXXXXXXXX
        XXXXX
    BBBBBB
    XXXXXXXX
    XXXXXXXX
    XXXXXX
    XXXXXX
    XXXXX
    XXXXX XXXXXXXXX XXXXXXXXXXXXXXBBBBBBBBBB
    BBB BBB BB BBBBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXFFFFFFFFFFX XX
    BBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX
    XXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u"Yes, I'm sure") X XX
    XXXXXXX
BBBBBBBB

