BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBB BBBBBB BBBBBBBBBB BBBBB BBBBBB

BBBBB BBBBBBBBBB

XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XX
XXXXXX XXXXXXXXXXXXXXXX
XXXXXXXX X
    XXXXXX XXXXXX
    XXXXXXXXXXXXX XXXXXX
X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBB

XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
XXX X X XXXXXXXXXXXXXX

XXXXXXXXXXXXXXXXXX XXXXXXXX XX X
  XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXX
XXX
XXXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
XX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Home') XXXX
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXXX
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXXX 
XXXXXX
BBBBBBBB


BBBBB BBBBBBB
    XXXXX XXXXXXXXX XXXXXXXXXXXXXXBBBBBBBBBB
    XXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        BB BBBBB
            BBB BBBBBBBB BBBBBB BBBBB BB BBBBB
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
             XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFF XXXXXXXXXXXXXXXXXX
            BB BBB BBBBB
                XXXXXXX
                XXXXXXX
                    XXXXXXXX gettext(u'Nothing to bill, all lines have size&times;quantity 0.') XXXXXXXXXX
                XXXXXXXX
                XXXXXXXX
            BBBB
                XXXXXXX
                XXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX
                XXXXXXX
                BBB BBBB BB BBBBB
                XXX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXBBBBXXXXBBBBBXX
                    XXXX
                        XX XXXXXX FFFFFFFFFXXFFFFXXXX
                        BBB BBBBBBBB BB BBBBBBBBBBBBBB
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX 
                        BBBBBB
                    XXXXX
                    XXXX FFFFFFFFFFFFXXXXX
                    XXXX FFFFFFFFFFFFFFFFXXXXXXX FFFFFFFFFFFFFFFFXXXXX
                    XXXX
                        XXXXXX FFFFFFFFFFFFFFFF XXXXXX
                        BBB BBBBBBBB BB BBBBBBBBBBBBBBXXXX FFFFFFFFFFFFFFFF XXXXXXBBBBBB
                    XXXXX
                XXXXX
                BBBBBB
            BBBBB
            XXXXXXXX
            XXXXXXXX
            XXXXXXXXXXX
            XXXXXX
            XXXXXX
            BBBBBB
            
        BBBB
            
        BBBBB
    XXXXXX
    BBB BBB BB BBBBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXFFFFFFFFFFX XX
    BBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XX
    XXXXXX XXXXXXXXXXXXX XXXXXXXBB BBBB BB B gettext(u'Yes, create bills') BBBB gettext(u'Next') BBBBBX XX
    XXXXXX
    XXXXXXX
BBBBBBBB
