BBBB BBBB BBBBB

XXXXXX
XXXXXX
    XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXX
    XXXXX X
       XXXXX XXXXXXX XXXXXXX
    X
    XXXXX X
       XXXXXXXXXX XXXXX
       XXXXXXXXXXXX XXXXX
       XXXXXXXXXX XXXXX
    X
    XXXXX XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXX
    X
    XXXXX XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXX
    X
    XXXXX XX X
        XXXXXX XXXXXX
        XXXXXXXXXXXXXXXXX XXXXX
    X
    XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXX
    X
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXX
    X
    XXXXXXXX
XXXXXXX
XXXXXX

XXXXXX XXXXXXXXXXXXX
XXX XXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Services') XXXXX
    XXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Active') XXXXX
    XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Cancelled') XXXXX
    XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Nominal price') XXXXX
    XXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Number') XXXXX
XXXXX
BBB BBBBBBBB BBBB BB BBBBBBBB
XXXX
    XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
XXXXX
BBBBBB
XXXX
    XXX XXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'TOTAL') XXXXXXXXX
    XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
XXXXX
XXXXXXXX

XXXXXXX
XXXXXXX
